#
# more information can be found here http://sonata-project.org/bundles/admin
#
# @author Christian Torres <chtorrez@gmail.com>
# @version 1.0
# @created 2012-04-21 20:36
#
sonata_admin:
    # default value, change it to sonata.admin.security.handler.acl to use ACL
    security:
        handler: sonata.admin.security.handler.role

    title:      %sonata_admin.title%
    title_logo: %sonata_admin.logo_title%
    templates:
        # default global templates
        layout:  SonataAdminBundle::standard_layout.html.twig
        ajax:    SonataAdminBundle::ajax_layout.html.twig

        # default value if done set, actions templates, should extends a global templates
        list:    SonataAdminBundle:CRUD:list.html.twig
        show:    SonataAdminBundle:CRUD:show.html.twig
        edit:    SonataAdminBundle:CRUD:edit.html.twig

    dashboard:
        blocks:
            - { position: left, type: sonata.admin.block.admin_list }
#            - { position: right, type: sonata.admin_doctrine_orm.block.audit}
#            - { position: right, type: sonata.block.service.text, settings: { content: "<h2>Welcome to the Sonata Admin</h2> <p>This is a <code>sonata.block.service.text</code> from the Block Bundle, you can create and add new block in these area by configuring the <code>sonata_admin</code> section.<br /> <br /> For instance, here a RSS feed parser (<code>sonata.block.service.rss</code>):</p>"} }
#            - { position: right, type: sonata.block.service.rss, settings: { title: Sonata Project's Feeds, url: http://sonata-project.org/blog/archive.rss }}
