#
# more information can be found here http://sonata-project.org/bundles/admin
#
# @author Christian Torres <chtorrez@gmail.com>
# @version 1.0
# @created 2012-04-21 22:27
#
sonata_user:
    security_acl: false
    google_authenticator:
        enabled: false
#        server: sonata-project.org

